version: '3.9'

services:
  webserver:
    image: nginx:alpine
    container_name: webserver
    tty: true
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./dockers/nginx/logs:/etc/nginx/logs
      - ./dockers/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - mysql
    networks:
      - our-network
    restart: always
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    volumes:
        # Add docker-entrypoint-initdb.d
      # - ./dockers/init:/docker-entrypoint-initdb.d
      - ./dockers/mysql:/var/lib/mysql
    environment:
      # Add database
      # MYSQL_DATABASE: simple
      # MYSQL_USER: user
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    ports:
      - 8000:80
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      # - PMA_ARBITRARY=1
      # - PMA_HOST=mariadb
      # - UPLOAD_LIMIT=40M
    depends_on:
      - mysql
volumes:
  dockers:
networks:
  our-network:
    external: true
